# Generated by Django 4.1.2 on 2022-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='2022-10-13 19:53:37'),
        ),
    ]
