# Generated by Django 4.1.2 on 2022-10-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_history_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='2022-10-13 19:57:54'),
        ),
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ManyToManyField(to='shopApp.product'),
        ),
    ]
