# Generated by Django 4.1.2 on 2022-10-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_alter_history_data_remove_history_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='2022-10-20 23:31:32'),
        ),
    ]
