# Generated by Django 4.1.2 on 2022-10-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_alter_product_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='2022-10-27 21:34:22'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
